### ISSUE TITLE
Map Filter (see the details in the paragraph) 

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#101]
If you click by this: 
Start → Online → Find → Map Filter (the top right one) → Click on Submerged → You will find the Airship also changes when the Submerged is clicked (the final bug) 
e.g.
Airship Off; Submerged Off → Airship On; Submerged On
Airship Off; Submerged On → Airship On; Submerged Off
Airship On; Submerged Off → Airship Off; Submerged On
Airship On; Submerged On → Airship Off; Submerged Off

But each map option should be separated. 

Screenshot

Before any movement ↓
![2023-07-05 (1)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/cacfa762-5f39-44a4-9082-8bcc75f8c0f0)

After the first click on Submerged ↓
![2023-07-05 (2)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/56f91049-b816-40d6-b620-f7d9b9c7ad21)

After the second click ↓
![2023-07-05 (3)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/692d1e03-b427-432d-85f9-02d0f255a854)

Log
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11955318/LogOutput.log)

And I also met the bug from this [https://github.com/SubmergedAmongUs/Submerged/issues/85](url)
Join any game or even the practice mode. While at the beginning distributing roles or loading meeting UI, the chat button appears.

**Comment by Alexejhero** [comment]
Thank you for the report, this will be fixed in the next version! :)
