### ISSUE TITLE
I think I found a clue about the chat button issue

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#102]
Look at these

The vanilla game ↓
![2023-07-07 (2)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/56ea3bb7-1851-4b1b-9a0d-3a209452a1ce)
Easy to see, when you open the chat box and then open the map, the map is in front of the chat box. 

With Submerged ↓
![2023-07-07 (1)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/91685c7c-eb3f-4ead-912b-7c769704f853)
Oh no! The layers are wrong. 

So I think this is also a layer issue.

**Comment by Alexejhero** [comment]
This will be fixed in the next update. Thank you for the help.
