### ISSUE TITLE
Vent Bug

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#103]
First, from second floor, jump into the admin vent and go down to first floor. Then go to any floor and jump into the central vent. You will find yourself suddenly transport to the outside of the map and then back to the vent. (The game isn't affected, but it's just too strange and not what a vent usually does. )

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11994427/LogOutput.log)

**Comment by Alexejhero** [comment]
Thank you for the bug report, it will be fixed in the next update!
