### ISSUE TITLE
Pet struggling while in the engine special vent 

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#106]
If you fall into the engine vent, your pet has probability to be struggling underneath the vent (Other times your pet would be standing there doing nothing). So I think maybe the pet should be invisible while in that vent, and that maybe why sometimes more than one player can jump into that vent. 

Photo of the struggling pet ↓
![2023-07-11 (2)](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/9727a1fc-bd03-48cf-9021-62db7977d475)

**Comment by Alexejhero** [comment]
It's a minor visual annoyance, but we won't be changing it. Messing with the pet can lead to other bugs and conflicts with other mods.

**Comment by Alexejhero** [comment]
changed my mind
