### ISSUE TITLE
chat is available during the game with Town of us mod

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#107]
**Describe the bug**
chat is available during the game with Town of us mod

**To Reproduce**

**Expected behavior**

**Screenshots**
![20230711131335_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/6a434445-b58d-4abd-857b-fa24ea63b1cc)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.27s]
 - Submerged: [e.g. 2023.7.9s]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/12012442/LogOutput.log)

**Additional context**
chat is available during the game with Town of us mod

**Comment by Alexejhero** [comment]
Town of Us issue, we don't touch the chat in any way

**Comment by Tommy-XL** [comment]
Lovers can chat while playing :/

**Comment by Alexejhero** [comment]
Oh yeah lmao didn't even notice
