### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#108]
**Is your feature request related to a problem? Please describe.**
Among us updated,please make update submergedd for new version among us

**Describe the solution you'd like**

**Additional context**
Among us updated,please make update submergedd for new version among us

**Comment by Alexejhero** [comment]
https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.7.9-beta.6

**Comment by Alexejhero** [comment]
Oh wait there's a new version lmao

**Comment by ArslanShakirov** [comment]
> Oh wait there's a new version lmao

ok

**Comment by Alexejhero** [comment]
Will be updated in the next release
