### ISSUE TITLE
displays airship instead of submerged

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#109]
**Describe the bug**
 I created a room with submerged map I called a friend to check how it works in public lobbies he installed only submerged in the end he sees my lobby but the game for some reason displays it as airship not submerged

**To Reproduce**

**Expected behavior**

**Screenshots**

![msg-1964244439-1079](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/050ef0a2-be9e-4c68-8d9c-d57fe9c2893d)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.7.11s]
 - Submerged: [e.g. 2023.7.12s]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/12027362/LogOutput.log)

**Comment by Alexejhero** [comment]
I will investigate this issue soon

**Comment by ArslanShakirov** [comment]
ok

**Comment by Alexejhero** [comment]
thanks for the report, will be fixed in the next update.
