### ISSUE TITLE
Cannot connect to steam account

### ISSUE THREAD

**Issue by jmxamongusmodder** [SubmergedAmongUs/Submerged#11]
Before i could but with submerged i cant.

**Comment by AlexejheroYTB** [comment]
Are you using any other mods?

**Comment by jmxamongusmodder** [comment]
> Are you using any other mods?

nope

**Comment by AlexejheroYTB** [comment]
Create a file called `steam_appid.txt` in your Among Us directory. In that file, type `945360`. Afterwards, restart among us and try logging in again.

**Comment by jmxamongusmodder** [comment]
> Create a file called `steam_appid.txt` in your Among Us directory. In that file, type `945360`. Afterwards, restart among us and try logging in again.

ok

**Comment by jmxamongusmodder** [comment]
wait i already have that... but it wont work even with it already being there.

**Comment by AlexejheroYTB** [comment]
Can you please show me a screenshot of the error you are receiving?

**Comment by jmxamongusmodder** [comment]
> Can you please show me a screenshot of the error you are receiving?
 
ok i will
hold on

**Comment by jmxamongusmodder** [comment]
![btuh](https://user-images.githubusercontent.com/80003646/167269232-0b218af9-ddfe-4623-af10-55e3a0266d6a.PNG)
here ya go

**Comment by jmxamongusmodder** [comment]
> ![btuh](https://user-images.githubusercontent.com/80003646/167269232-0b218af9-ddfe-4623-af10-55e3a0266d6a.PNG) here ya go

never happened before i downloaded submerged

**Comment by AlexejheroYTB** [comment]
Are you launching Among Us from steam or from the .exe?

**Comment by jmxamongusmodder** [comment]
> Are you launching Among Us from steam or from the .exe?

steam

**Comment by AlexejheroYTB** [comment]
Rename the `winhttp.dll` file in your Among Us directory to something else, and then try launching Among Us.

This will disable all mods from loading.

Afterwards, see if you are able to login through steam.

(You can restore mods by renaming the file back to `winhttp.dll`.)

**Comment by jmxamongusmodder** [comment]
> Rename the `winhttp.dll` file in your Among Us directory to something else, and then try launching Among Us.
> 
> This will disable all mods from loading.
> 
> Afterwards, see if you are able to login through steam.
> 
> (You can restore mods by renaming the file back to `winhttp.dll`.)

ok

**Comment by jmxamongusmodder** [comment]
> > Rename the `winhttp.dll` file in your Among Us directory to something else, and then try launching Among Us.
> > This will disable all mods from loading.
> > Afterwards, see if you are able to login through steam.
> > (You can restore mods by renaming the file back to `winhttp.dll`.)
> 
> ok

still cant work even when i did that

**Comment by AlexejheroYTB** [comment]
Rename the file back to `winhttp.dll` if you haven't already, then relaunch Among Us and try to reproduce the issue.

If it still occurs, please send me the following files: 
- `Among Us/BepInEx/LogOutput.log`
- `%appdata%/../LocalLow/Innersloth/Among Us/Player.log`

**Comment by jmxamongusmodder** [comment]
> Rename the file back to `winhttp.dll` if you haven't already, then relaunch Among Us and try to reproduce the issue.
> 
> If it still occurs, please send me the following files:
> 
> * `Among Us/BepInEx/LogOutput.log`
> * `%appdata%/../LocalLow/Innersloth/Among Us/Player.log`

ok

**Comment by jmxamongusmodder** [comment]
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8646043/LogOutput.log) bepinex

[Player.log](https://github.com/SubmergedAmongUs/Submerged/files/8646044/Player.log) amog us

**Comment by AlexejheroYTB** [comment]
The logs seem fine. Maybe steam had downtime? Can you login now?
If not, try verifying Among Us game files

![image](https://user-images.githubusercontent.com/32238504/167291740-d5491b2d-637d-4483-8c17-1d0d384c02cf.png)

**Comment by jmxamongusmodder** [comment]
> The logs seem fine. Maybe steam had downtime? Can you login now? If not, try verifying Among Us game files
> 
> ![image](https://user-images.githubusercontent.com/32238504/167291740-d5491b2d-637d-4483-8c17-1d0d384c02cf.png)

k

**Comment by jmxamongusmodder** [comment]
> > The logs seem fine. Maybe steam had downtime? Can you login now? If not, try verifying Among Us game files
> > ![image](https://user-images.githubusercontent.com/32238504/167291740-d5491b2d-637d-4483-8c17-1d0d384c02cf.png)
> 
> k

verifyed intergrity did what u said still wont work

**Comment by AlexejheroYTB** [comment]
Does this issue still occur for you even without having Submerged loaded?

**Comment by jmxamongusmodder** [comment]
> Does this issue still occur for you even without having Submerged loaded?

yes

**Comment by AlexejheroYTB** [comment]
Well, in that case, I'm sorry but I can't help you as this is not a Submerged issue. Try looking for help someplace else.
