### ISSUE TITLE
Host only version

### ISSUE THREAD

**Issue by SharkSonic45** [SubmergedAmongUs/Submerged#110]
**Is your feature request related to a problem? Please describe.** It’s not really a problem but I would to put down a request I’ve read somewhere that if the host has the map everyone can enjoy it like town of host and project lotus

**Describe the solution you'd like**
I think there should be a host only Version where if the host has the mod everyone can enjoy the mod so that everyone is happy.

**Comment by Alexejhero** [comment]
As explained in #55 this is not possible

**Comment by SharkSonic45** [comment]
Oh.          Shit I must’ve missed that one
