### ISSUE TITLE
The Whale Shark Not in Sight -24 ? ! 

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#111]
![2023-07-16](https://github.com/SubmergedAmongUs/Submerged/assets/129944434/1b454785-5c97-4b26-8666-78f719d5e8f6)
The 70s countdown is correct, but it counts from about 20s to -50s. 

Ps.The first line of the tasks is the spot whale shark task which I'm talking about.

**Comment by Alexejhero** [comment]
thanks for the report, will be fixed in the next version :)
