### ISSUE TITLE
HnS music bug

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#112]
**Describe the bug**
HnS plays the wrong music at the start

**To Reproduce**
1. Start HnS game
2. Thats it lol

**Expected behavior**
When playing as the crewmate in Hide n Seek you can hear the wrong music at the beginning of the round (it plays music that should play when you're doing a task). After entering a task it plays normal music.

**Version:**
 - Among Us: 2023.7.12s
 - Submerged: 2023.7.17-beta 8
 
 File is too big so I uploaded it to YT: https://youtu.be/mKAo81_0bro

**Comment by Alexejhero** [comment]
Thank you for reporting, this issue will be fixed in the next update.
