### ISSUE TITLE
at the beginning of the sabotage of light amogus is not displayed 

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#114]
**Describe the bug**
at the beginning of the sabotage of light amogus is not displayed 

**To Reproduce**

**Expected behavior**

**Screenshots**

![20230718151802_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/bca90d8d-2398-4c31-a64d-7a29243ceef6)

**Version (please complete the following information):**
 - Among Us: [e.g. 2022.7.12s]
 - Submerged: [e.g. 2023.7.17s]

**Log file**

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/12122572/LogOutput.log)

**Additional context**

**Comment by Alexejhero** [comment]
Works as intended
