### ISSUE TITLE
S-Chinese (简体中文)

### ISSUE THREAD

**Issue by alonghd** [SubmergedAmongUs/Submerged#115]
**What language(s) do you want to help us with?**
S-Chinese (简体中文)

**How can we contact you?**
3454017820@qq.com

**Additional information**
I'm along and I want to improve the Simplified Chinese translation of Submerged.

**Comment by Alexejhero** [comment]
Currently there is only one missing Simplified Chinese translation for Submerged

The only translation we are missing is `Waiting for the Impostor... ({0}s)`

This text appears in the same place where `Waiting for Other Players... ({0}s)` appears in (which was translated as `等待其他玩家... ({0}s)`

**Comment by Sand-and-Beans** [comment]
> Currently there is only one missing Simplified Chinese translation for Submerged
> 
> The only translation we are missing is `Waiting for the Impostor... ({0}s)`
> 
> This text appears in the same place where `Waiting for Other Players... ({0}s)` appears in (which was translated as `等待其他玩家... ({0}s)`
> 
> If you would like to help, are there any other translations that need to be updated? If not, it's just the one above

It can be translated as `等待内鬼... ({0}s)`

**Comment by alonghd** [comment]
"Impostor" translated as "伪装者" in offical SChinese, so I think "Waiting for Other Players... ({0}s)" should be translated as "等待伪装者... ({0}s)"
&nbsp;


孤岛荒年&nbsp;-&nbsp;along
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 上午10:23
收件人: ***@***.***&gt;; 
抄送: "孤岛荒年 - ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SubmergedAmongUs/Submerged] S-Chinese (简体中文) (Issue #115)





  
Currently there is only one missing Simplified Chinese translation for Submerged
 
The only translation we are missing is Waiting for the Impostor... ({0}s)
 
This text appears in the same place where Waiting for Other Players... ({0}s) appears in (which was translated as 等待其他玩家... ({0}s)
 
If you would like to help, are there any other translations that need to be updated? If not, it's just the one above
  
It can be translated as 等待内鬼... ({0}s)

**Comment by Alexejhero** [comment]
Thank you for the help, the translation will be included in the next update.
