### ISSUE TITLE
Submerged 'breaking' the task map for vanilla maps

### ISSUE THREAD

**Issue by NotSugden** [SubmergedAmongUs/Submerged#117]
**Describe the bug**
The submerged mod appears to be modifying the task map to show a red circle around the yellow exclamation point for the sabotages on submerged. In doing this it modifies the task map for every map, and shows a regular yellow circle (with no outline) for the lights and reactor sabos only. O2 does not have this issue.

It is also put underneath the doors sabo for the case of the lights sabo.

**To Reproduce**
Start a match of skeld/mira/polus - sabo lights or reactor

**Expected behavior**
The expected behaviour should be that the icon does not appear on the map for the vanilla maps, or the mod should make this new behaviour consistent across all maps (however that would be out of scope for this mod)

**Screenshots**

**Version (please complete the following information):**
 - Among Us: 2023.7.12s
 - Submerged: 2023.7.24s

**Log file**
N/A

**Additional context**:
N/A

**Comment by Alexejhero** [comment]
Will be fixed in the next version i guess
