### ISSUE TITLE
Incorrect outfit sprite used in Submerged exile

### ISSUE THREAD

**Issue by Tommy-XL** [SubmergedAmongUs/Submerged#12]
**Describe the bug**
Incorrect display of pants skin during exile

**Screenshots**
Exile on Submerged:
![Screenshot_20220508_144144](https://user-images.githubusercontent.com/104814436/167285190-52db7036-d9ee-4324-a61e-30beaa42efc7.jpg)

Exile on The Airhip:
![IMG_20220508_144200](https://user-images.githubusercontent.com/104814436/167285218-ac88669b-75ac-4b07-85b9-ea80fb1dc969.jpg)

**Version:**
 - Among Us: [e.g. 2022.3.29s]
 - Submerged: [e.g. 2022.5.2]

**Comment by AlexejheroYTB** [comment]
Are you using any other mods?

**Comment by Tommy-XL** [comment]
I used the Town Of Us mod (I know it's incompatible with the map) but I want to say that The Other Roles mod has the same bug

**Comment by Tommy-XL** [comment]
As proof, here is a screenshot with The Other Roles mod:
![Screenshot_20220508_150621](https://user-images.githubusercontent.com/104814436/167285749-89e0acb1-a9f5-43d6-b0e7-c8102b8ed2ce.jpg)

**Comment by AlexejheroYTB** [comment]
Ah, I see what you mean now. You're saying that the pants are using the default image instead of the "bendy" exile image. 😆

**Comment by AlexejheroYTB** [comment]
Fixed in v2022.5.8
https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.8
