### ISSUE TITLE
Null Ref Spam In Logs

### ISSUE THREAD

**Issue by AlchlcDvl** [SubmergedAmongUs/Submerged#120]
**Describe the bug**
The BepInEx log is spammed with null ref errors

**To Reproduce**
(Might be a compatibility issue instead, the mod list is in the screenshots section)
1. Open a local lobby
2. Press F1 and spawn bots to play
3. Set the map to any map that's not Submerged

**Expected behavior**
Honestly I have no idea what it's supposed to do exactly, it's not a critical bug, just a really annoying thing to see in the logs when trying to look for errors in your own mod

**Screenshots**

![image](https://github.com/SubmergedAmongUs/Submerged/assets/56699741/99b3774b-b252-4a56-a9b0-2bbcb53fe7fa)

**Mod List**

![image](https://github.com/SubmergedAmongUs/Submerged/assets/56699741/dc4bb44c-d772-495e-9028-04df01444ccb)

**Versions**
 - AU - 2023.7.12s
 - Sub - 2023.8.2

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/12280257/LogOutput.log)

**Additional context**
The mods I'm using are not out yet so here's their dll files in case it might actually be a compatibility issue

[plugins.zip](https://github.com/SubmergedAmongUs/Submerged/files/12280283/plugins.zip)

The mods are:- Town Of Us Reworked, the mod that I'm working on and a custom build of UnityExplorer given to me by MyDragonBreath along with the usual Reactor and Submerged files

**Comment by AlchlcDvl** [comment]
i just realised mdb's ue doesn't load so you can ignore that part of the mod list

**Comment by Alexejhero** [comment]
I cannot reproduce this without Reworked.dll

I will try with and see the results

**Comment by Alexejhero** [comment]
There is nothing that could throw that null ref in that property, unless `PlayerCounter_TMP` is renamed, destroyed or its children are modified

**Comment by AlchlcDvl** [comment]
i see then it might be an issue on my end

**Comment by AlchlcDvl** [comment]
but i mostly copy pasted the vanilla code and modified some parts of it so i'm not sure why it's being an issue

although earlier when i didn't do such a thing, the logs would be spammed with null refs within the vanilla code that than the mod itself so to fix that i simply rewrote it with a bool prefix returning false

the only time i actually modify it myself is here

![image](https://github.com/SubmergedAmongUs/Submerged/assets/56699741/79c28314-9b98-46e2-9406-66a3a9957210)

**Comment by AlchlcDvl** [comment]
so i temporarily disabled any modifications to PlayerCounter and the issue still persists

so would it possible for you to instantiate a new PlayerCounter and edit that to resolve any conflicts?

**Comment by Alexejhero** [comment]
I'm not editing the player counter, I am already cloning it, but I need to grab the original in order to do that.

I've changed from grabbing it by name to grabbing GameStartManager by type, this should mean that it won't be a problem even if you change it in other mods,
