### ISSUE TITLE
Disable map installation check for dummy players in the lobby as well.

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#121]
**Is your feature request related to a problem? Please describe.**
I try to play Submerged using a dummy player for debugging purposes in local games, etc., but an error occurs and I cannot play.

**Describe the solution you'd like**
Disable dummy player installation checks in the lobby
If there are concerns online, I would like to see just local games disabled.

**Additional context**
rerated my mods issues https://github.com/yukieiji/ExtremeRoles/issues/310

**Comment by Alexejhero** [comment]
I will see what I can do about this but in the meantime you can patch `Submerged.Loading.CustomPlayerData:HasMap` to return true

**Comment by Alexejhero** [comment]
Will be changed in the next version, I'm not sure when that will be released though...

**Comment by Alexejhero** [comment]
Changed in the next release
