### ISSUE TITLE
PlayerControl.Exiled() called twice

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#123]
**Describe the bug**
PlayerControl.Exiled() is called twice when the player is exiled
I checked with Skeld and AirShip.

**To Reproduce**
1. Play Skeld or AirShip
2. Exiled player

**Expected behavior**
It seems correct that this process is called only once at the time of exile.

**Version (please complete the following information):**
 - Among Us: 2023.7.12
 - Submerged: 2023.07.24 and 2023.08.02

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/12371704/LogOutput.log)
"[Info   :Extreme Roles] Call exiled!!!!!" (PlayerControl.Exied() is called) is called twice, this is the log of one exiled.

**Additional context**
I have another mod installed, but uninstalling only the submerged fixed this problem

**Comment by yukieiji** [comment]
I applied a Patch to `ExileControllerPatches.BeginPatch` and this bug no longer occurs.
`ExileController.Begin` to display the number of people in other teams in my mod, so it seems that there was a conflict and this glitch was occurring.

**Comment by Alexejhero** [comment]
Okay I understand the problem. However we need that patch because otherwise the exile text isn't properly displayed sometimes...

**Comment by Alexejhero** [comment]
Can this issue be closed then?

**Comment by yukieiji** [comment]
I have confirmed that even with only the Begin patch of my mod working, in rare cases, the exile text is not displayed.
I have also confirmed that it always disappears after it is no longer displayed.

**Comment by Alexejhero** [comment]
So in order to facilitate mod compatibility, I've taken out the Submerged patch on ExileController begin into its own method which you can patch instead of the original ExileController.Begin if Submerged is installed. How is that?

**Comment by Alexejhero** [comment]
So mod devs would patch this method with the same patch that you would apply to ExileController.Begin

![image](https://github.com/SubmergedAmongUs/Submerged/assets/32238504/69ef9448-f0ef-42e3-ab14-57ae42319c2e)

**Comment by yukieiji** [comment]
I have the following patched in my mod, how do I patch it?
![ExiledPatch](https://github.com/SubmergedAmongUs/Submerged/assets/40425798/f635e1d5-42dd-48d7-aacb-89011beb9fd4)

**Comment by Alexejhero** [comment]
Something like this maybe?

![image](https://github.com/SubmergedAmongUs/Submerged/assets/32238504/acc6e739-2657-4b81-8f1a-f07f981c888f)

**Comment by Alexejhero** [comment]
If you call Apply from the mod's entry point it might load before submerged and not detect it, in this case you can either make your mod load after submerged by adding `[BepInDependency("Submerged", BepInDependency.DependencyFlags.SoftDependency)]` to your plugin class or by calling `Apply` at a later point

**Comment by yukieiji** [comment]
Thank you, I would think fixes are done with [this commit](https://github.com/yukieiji/ExtremeRoles/commit/73825fcb4cda9ac94718c02c9539e2f1876105cd).

**Comment by Alexejhero** [comment]
I hope this is an acceptable compromise I don't know what else I could do to improve compatibility here. 

I thought about checking ExileController.Begin for patches from other mods and unpatching them from there and instead repatching them on ExileControllerPatches.ExileController_Begin, but that's not possible because in one case ExileController is __instance and in the other case its HarmonyArgument(0)

**Comment by yukieiji** [comment]
In v2024.8.1 this patch has been removed, is it no longer necessary to do anything?

**Comment by Alexejhero** [comment]
Yeah you don't need to worry about this anymore, it should work just like any other map.
