### ISSUE TITLE
Submerged Auto Updater

### ISSUE THREAD

**Issue by AlchlcDvl** [SubmergedAmongUs/Submerged#124]
**Is your feature request related to a problem? Please describe.**
Not really a problem but seeing auto updaters in other mods for this one feels off

**Describe the solution you'd like**
A built in auto updater

**Additional context**
I understand that this might be of a lower priority compared to other things but would be cool to see later on

**Comment by Alexejhero** [comment]
There's no plans to add an auto-updater
