### ISSUE TITLE
Danger level cant reach 5 while Ghost

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#125]
**Describe the bug**
While playing as a Ghost in HnS Danger meter cant get Level 5

**To Reproduce**
1. Play HnS
2. Die (in game)
3. See error

**Version:**
 - Among Us: 2023.7.12s
 - Submerged: 2023.8.2s
 
![Снимок экрана 2023-08-28 224827](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/c056f010-fdac-428b-8f84-debc8fc666d3)

**Comment by Alexejhero** [comment]
Fixed in the next release
