### ISSUE TITLE
The game closes randomly and others .

### ISSUE THREAD

**Issue by damisub** [SubmergedAmongUs/Submerged#129]
**Describe the bug**
The game is closing at random times and its impossible to play . Sometimes when I click something the chat or somthing else it closes i dont know why .

**To Reproduce**
1. Enter in the game 
2. Its gona close at random times

**Expected behavior**
Please fix this fast .

**Screenshots**

https://github.com/SubmergedAmongUs/Submerged/assets/148007374/0d5f18ea-03a8-4f3f-b707-cab8be0b4457

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.10.29]
 - Submerged: [e.g. 2023.11.2]

**Additional context**
and I saw some walls missing and please fix them if you can .

![image](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/c8694689-fcf4-4e96-b8a4-5912194fe5b2)

![image](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/b7920cc1-71c1-4dc1-bf58-9a2b40d2c430)

And one final thing is it normal for this to appear every single time I enter the game ???

![image](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/bef03504-ac98-454e-9d96-e044f8d99847)

sorry for low quality screenshot .

**Comment by Alexejhero** [comment]
The walls are missing on purpose, there is not supposed to be a wall there because there is no room there on the lower deck.

**Comment by damisub** [comment]
There are some spots that look like the wall is missing and about the game closing randomly ?

**Comment by damisub** [comment]
About the walls . That is how the map is suppose to look . The circled walls are missing in the game and if you enter the game and go to them they are missing. About the closing it happens very often and its impossible to play but no is just closing the game for no reason . Sometimes I cant log in the game because it says bedinex couldn't start or something but sometimes I can . Its weird because it says nothing its just closing and thats it .

**Comment by Alexejhero** [comment]
What are your computer specifications? (CPU, GPU, Memory, etc)

**Comment by Alexejhero** [comment]
Those walls aren't missing so I'm not sure what you are talking about, can you record the issue please?

**Comment by damisub** [comment]
just a sec

**Comment by damisub** [comment]
![IMG_20231102_194235](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/cd840c97-ffce-47b9-9984-861f4a451a23)
![IMG_20231102_194227](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/c485cb39-2682-4bad-9d48-a9fe5050b4a1)
![IMG_20231102_194218](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/d93f30e9-a9b3-4858-96a4-07d7a37f14f4)
![IMG_20231102_194245](https://github.com/SubmergedAmongUs/Submerged/assets/148007374/21e3117e-2ec1-42bf-a798-ea806ed8291d)

Thanks for waiting

**Comment by Alexejhero** [comment]
You either have a corrupted version of Submerged, or your computer does not meet the minimum requirements for running Submerged.

Try to redownload Submerged and see if that fixes the problem

**Comment by damisub** [comment]
I tried that multiple times and it didn't work .

**Comment by damisub** [comment]
processor : 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
RAM : 8 GB
GPU : Intel(R) Iris(R) Xe Graphics

hope its useful

**Comment by damisub** [comment]
but what can I do to fix this ?

**Comment by Alexejhero** [comment]
Those errors are normal. If they are the only errors in your log, and Submerged still has problems for you after reinstalling it multiple times, then I'm afraid it's due to hardware incompatibilities. In this case, it probably is from the low amount of VRAM that your graphics card has (128MB).
