### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by alonghd** [SubmergedAmongUs/Submerged#13]
**What language(s) do you want to help us with?**
Let us know what language(s) you want to translate Submerged into.
Chinese(简体中文)
**How can we contact you?**
Please leave an email or Discord tag that we can reach you at.
_removed_
**Additional information**
Add any other information here.
None

**Comment by AlexejheroYTB** [comment]
Simplified Chinese translations have already been submitted by someone else and will be available in the next update.
