### ISSUE TITLE
submerged cosmetics and another thing

### ISSUE THREAD

**Issue by AppcircleUser** [SubmergedAmongUs/Submerged#130]
**Is your feature request related to a problem? Please describe.**
not a problem but I think it would be a nice qol thing to add both themed cosmetics and controller support

**Describe the solution you'd like**
submerged themed cosmetics for players of the mod, like the base maps having both cosmetics and controller support

**Additional context**
this is a submerged nameplate in las monjas
![Screenshot_20231111_150204](https://github.com/SubmergedAmongUs/Submerged/assets/94975269/3b50e8ac-a8df-4448-b61a-227967cb8c47)

also if you saw my previous issue I did buy among us

**Comment by Alexejhero** [comment]
Submerged has entered long term support mode, meaning that we are happy with the product we have right now, and there won't be many more features added. Thanks for your suggestion, but there is no plan to add cosmetics at this time.
