### ISSUE TITLE
Update to v2024.3.5

### ISSUE THREAD

**Issue by Alexejhero** [SubmergedAmongUs/Submerged#143]
Mod is broken right now (Epic)

![](https://i.imgflip.com/2p3dw0.jpg?a474888)

**Comment by Pietrodjaowjao** [comment]
Horse mode is gone, but looks like they added a new mode called Long mode, i will see later.

**Comment by Pietrodjaowjao** [comment]
it is in AprilFoolsMode class

**Comment by Alexejhero** [comment]
Seems like there's an issue with the anti-cheat on official servers
