### ISSUE TITLE
Better Traditional Chinese translations

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#15]
**What language(s) do you want to help us with?**
Traditional Chinese 
**How can we contact you?**
_removed_
**Additional information**
i think the original translations is bad(like google translations?), so i make better.

Location:
Observatory ----> 天文台
Cafeteria ----> 餐廳
Admin ----> 管理室
Lounge ----> 休息室
Meeting Room ----> 會議室
Upper Lobby ----> 上層大廳
Lower Lobby ----> 下層大廳
Communications ----> 通訊室
Research ----> 研究室
Medical ----> 醫療室
Upper Central ----> 上層中心
Lower Central ----> 下層中心
Ballast ----> 水壓房
Engine Room ----> 引擎室
Security ----> 保全室
Storage ----> 儲藏室
Electrical ----> 電氣室
Filtration ----> 過濾室
Hallway ----> 走廊

Tasks:
Plug Leaks ----> 堵住漏水處
Align Telescope ----> 校正望遠鏡
Clean Glass ---- 擦拭玻璃
Clear Urchins ----> 清理海膽
Cycle Reactor ----> 循環引擎反應器
Fix Wiring ----> 修理線路
Spot Whale Shark ----> 觀察鯨鯊
Download Data ----> 下載資料
Upload Data ----> 上傳資料
Shoot Depth Charges ----> 射擊掉落的水雷
Microwave Lunch ----> 加熱食物
Reshelve Books ----> 整理書籍
Record Nav Beacon Data ----> 紀錄海洋導航信標資料
Submit Scan ----> 掃描身體
Mop Puddles ----> 拖乾地面
Oxygenate Sea Plants ----> 給予海洋植物氧氣
Diagnose Elevators ----> 診斷電梯
Dispense Water ----> 裝滿水瓶
Feed Pet Fish ----> 餵食寵物魚
Identify Specimen ----> 檢驗標本
Locate Volcanic Activity ----> 觀察火山地形
Purchase Breakfast ----> 購買早餐
Reconnect Piping ----> 重新連接水管
Reset Breakers ----> 重置斷路器
Start Submersible ----> 啟動潛水艇
Steady Heartbeat ----> 穩定心跳
Track Manta Ray ----> 追蹤鬼蝠紅
Unlock Manifolds ----> 解鎖岐管
Sort Scuba Gear ----> 整理潛水用具

Other Task translations
Spot Whale Shark:
In Range: ----> 出沒中:
Not Visible: ----> 尚未出沒:

Sabotages: (btw i don't translation vanila sabotage name)
Stabilize Water Levels ----> 穩定水位
Retrieve Oxygen Mask ----> 拾取氧氣面罩

System Translations:
Spawn Choose:
Upper Deck ----> 上層機艙
Lower Deck ----> 下層機艙

On Spawn Choose Screen:
Waiting For Other Players ----> 等待其他玩家
Loading... ----> 載入中...

that was all of this map task and location translations. pls changes thanks! :D

**Comment by AlexejheroYTB** [comment]
Added in v2022.5.15. Thanks for helping us translate!
https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.15
