### ISSUE TITLE
How can i make an event happen after floor choosing?

### ISSUE THREAD

**Issue by PHGaming121** [SubmergedAmongUs/Submerged#156]
i want to do something like: when everyone select floor, everyone will get teleported to a random place of the map

this places are already defined by me

didnt select a template because theres no "code help" template ._.

**Comment by GameTechGuides** [comment]
what do you mean ? if u wante Change players floor use `FloorHandler.RpcRequestChangeFloor(bool isUpper) `

**Comment by GameTechGuides** [comment]
i Recommande you to see at source code

**Comment by PHGaming121** [comment]
if u didnt understand, after every player spawned, everyone will get teleported to a random place (that i already defined)

so the steps are:
1: enable the option of Random Spawns
2: Start the game
3: Select floor
4: after everyone selected floor, everyone will get tped to a random place

**Comment by Alexejhero** [comment]
After the spawn in system finishes, you can just send an RpcSnapTo to teleport the player

**Comment by PHGaming121** [comment]
which method should i use?

**Comment by Alexejhero** [comment]
You can do something like transpiler patching this Deteriorate method [here](https://github.com/SubmergedAmongUs/Submerged/blob/main/Submerged/SpawnIn/SubmarineSpawnInSystem.cs#L44) or by checking the state in an update loop
