### ISSUE TITLE
Disable spawn minigame if setting is on

### ISSUE THREAD

**Issue by PHGaming121** [SubmergedAmongUs/Submerged#160]
This is for my Random spawn project

I already have done this, it works on first spawn, but after meeting end, it just black screens among us

The fact it doesnt give anyting like warnings or errors....

Also, could u plz add a "Code Help" issue template?

**Comment by Alexejhero** [comment]
You have a few ways of approaching this, like changing the state of the system, preventing the minigame from being opened, etc.
The important part is that if you want to remove this, you will need to remove both the system and the minigame.

Relevant code:
- [Minigame](https://github.com/SubmergedAmongUs/Submerged/blob/main/Submerged/SpawnIn/SubmarineSelectSpawn.cs)
- [System](https://github.com/SubmergedAmongUs/Submerged/blob/main/Submerged/SpawnIn/SubmarineSpawnInSystem.cs)
- [Patch that creates minigame](https://github.com/SubmergedAmongUs/Submerged/blob/main/Submerged/SpawnIn/Patches/DisplayPrespawnStepPatches.cs)

---

> Also, could u plz add a "Code Help" issue template?

![](https://cdn.7tv.app/emote/616fff1bb6d21adaffbeae44/4x.webp)

You should generally figure stuff like this on your own. I don't really have the time to provide code help, but I don't mind giving some tips here and there. 

This project was written like 3 years ago so to be honest even I don't know how I would tackle this problem. I am not going to look into it for you. However, what I wrote above should be a good starting point for figuring this out yourself.

**Comment by PHGaming121** [comment]
the main idea isnt only the random spawn, but porting submerged support to LITERALLY A HOST ONLY MOD (ik that sounds dumb because everyone needs submerged to play, BUT, this Host-Only is like, my favorite among us mod, so why not?)

**Comment by PHGaming121** [comment]
maybe when the "for devs" is updated...

**Comment by Alexejhero** [comment]
... It is literally not possible for Submerged to be made into a host only mod.........
