### ISSUE TITLE
How can i see if a Vector2/3 location is on a different floor

### ISSUE THREAD

**Issue by PHGaming121** [SubmergedAmongUs/Submerged#161]
like this:
lets say im on lower floor, and a thing that isnt a player is on upper floor, and i need to track this thing

since FloorHandler.GetFloorHandler doesnt allows u to use Vector2 or Vector3, and also, i dont want to use ArrowBehaviour, because im doing the tracking in other ways...

so, if the "thing" is on a diferrent floor, the arrows will point to nearest elevator, and then, when player and object are on same floor, the arrows will point to the location normally

**Comment by Alexejhero** [comment]
This kind of check is done in a bunch of different places in Submerged. Please take a look at the source code and figure it out yourself
