### ISSUE TITLE
 v2024.6.18 

### ISSUE THREAD

**Issue by AnthoYt** [SubmergedAmongUs/Submerged#164]
Bonjour, 

Lors de la mise à jour Among Us aujourd'hui j'aimerais savoir quand la map sera mis à jour pour les rôles ?
car je voulais live dessus avec ma communauté le 6 juillet.

**Comment by GameTechGuides** [comment]
> Bonjour,
> 
> Lors de la mise à jour Among Us aujourd'hui j'aimerais savoir quand la map sera mis à jour pour les rôles ? car je voulais live dessus avec ma communauté le 6 juillet.

hello the new update just get released and devs of submerged hasn't started on it so you may wait some weeks because they are a lot of breaking changes

**Comment by AnthoYt** [comment]
Oui je sais c'est pour ça que je demande, pensez vous le 6 juillet qu'elle sera dispo ?

**Comment by GameTechGuides** [comment]
> Oui je sais c'est pour ça que je demande, pensez vous le 6 juillet qu'elle sera dispo ?

i don't know i can update submerged but the devs dosen't allow to do it only them

**Comment by Alexejhero** [comment]
I cannot say for sure. I will let you know after I look at it in the following days

**Comment by GameTechGuides** [comment]
> I cannot say for sure. I will let you know after I look at it in the following days

ok

**Comment by Alexejhero** [comment]
I started updating the mod today, but I cannot finish until [Reactor](https://github.com/NuclearPowered/Reactor) updates first.

**Comment by Pietrodjaowjao** [comment]
can you create a pr so i can test then?

**Comment by AnthoYt** [comment]
Slt, le Reactor sera à jour d'ici pas longtemps

**Comment by GameTechGuides** [comment]
i may update reactor today if need

**Comment by PHGaming121** [comment]
so, reactor just "released" an update for 6.18 (its in actions tab 💀 ), so, i guess u can start work on the mod now...

**Comment by George20104886** [comment]
Don't worry about it people, I'm sure 5up and the team will update the map. They can take as long as they need to, it takes a lot of hard work to make, develop and update such a high-quality mod.

**Comment by PHGaming121** [comment]
@Alexejhero is this enough for an update start?
![image](https://github.com/SubmergedAmongUs/Submerged/assets/76562427/32cb8748-45ae-444a-967e-09b827a5a275)

**Comment by Alexejhero** [comment]
There are a handful of hard crashes that need to be fixed, this update might take some time

**Comment by ProSLYT** [comment]
> There are a handful of hard crashes that need to be fixed, this update might take some time

how long? can you give us like an ETA on it?

**Comment by chillultimated** [comment]
so in the end... Is there any information about the update? Just curious.

**Comment by Alexejhero** [comment]
I'll repost this here as well

>>> There are some major crashing issues which are out of my area of expertise so I do not know how to solve them. I've asked for help from another developer, but they have been a bit busy recently.

Hopefully we can start working on these problems relatively soon.

You can keep track of the update progress in the #165 PR, however I cannot provide a time estimate for when it will be finished.

**Comment by Aarix12** [comment]
Also in the new update they could fix the submerged cover in free mode and fix the problem that no game appears

**Comment by AnthoYt** [comment]
faut être patient, même si je suis curieux d'avoir la mise à jour. Courage à l'équipe. Hâte de jouer fin Août.

**Comment by Aarix12** [comment]
Or we could financially support the developers so that they release the update faster

**Comment by ProSLYT** [comment]
> Or we could financially support the developers so that they release the update faster

im too broke lol

**Comment by Alexejhero** [comment]
> Also in the new update they could fix the submerged cover in free mode and fix the problem that no game appears

Hm. what are you talking about? Is there a bug with this?

**Comment by Aarix12** [comment]
Ladies and gentlemen, they have updated it

PD:
link does not work

**Comment by Aarix12** [comment]
We will have to wait until tomorrow and we will have it for version 2024.6.18

**Comment by ProSLYT** [comment]
Finally

**Comment by Alexejhero** [comment]
Reactor hasn't updated yet, I'm waiting on that to happen first before I release the Submerged update

**Comment by ProSLYT** [comment]
> Reactor hasn't updated yet, I'm waiting on that to happen first before I release the Submerged update

does that mean submerged is ready for the new version?????

**Comment by AnthoYt** [comment]
peut-être

**Comment by ProSLYT** [comment]
Reactor already updated on july 29 LMAO

**Comment by Alexejhero** [comment]
Update released: https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2024.8.1/
