### ISSUE TITLE
among us sumerged

### ISSUE THREAD

**Issue by Lokman01234** [SubmergedAmongUs/Submerged#167]
Guys, when will you release the update 2024.6.25v submerged among us I have been waiting for too long ?

**Comment by Alexejhero** [comment]
There are some major crashing issues which are out of my area of expertise so I do not know how to solve them. I've asked for help from another developer, but they have been a bit busy recently.

Hopefully we can start working on these problems relatively soon.

You can keep track of the update progress in the #165 PR, however I cannot provide a time estimate for when it will be finished.
