### ISSUE TITLE
Polish translator

### ISSUE THREAD

**Issue by Andrzejone** [SubmergedAmongUs/Submerged#17]
**What language(s) do you want to help us with?**
Polish language (PL)

**How can we contact you?**

_removed_

**Additional information**

Uhm, If you ask about some experience in translating games, there Isn't any. But I was translator of ModManager by Matux also couple of community projects of other browser-based games.

**Comment by AlexejheroYTB** [comment]
Among Us does not have a Polish translation available, so unfortunately we cannot accept Polish translations for Submerged.
