### ISSUE TITLE
Add pics of the new map to README

### ISSUE THREAD

**Issue by adityaraute** [SubmergedAmongUs/Submerged#176]
**Is your feature request related to a problem? Please describe.**
Can't tell which map the repo is about. How does it look? Is it good enough for me to use?

**Describe the solution you'd like**
Some screenshots of the new map and gameplay in the README would be great.

**Comment by Alexejhero** [comment]
There are literally screenshots already in the readme

**Comment by adityaraute** [comment]
Oh, they were minimised.
I'm so sorry, didn't notice.
