### ISSUE TITLE
Some of the submerged objects aren't destroy 

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#177]
**Describe the bug**
Playing submerged will leave some objects undestroy and memory hungry.

**To Reproduce**
1. Play Submerged
2. Play another map after playing
3. Get a list of all Unity objects
4. Objects not destroyed due to some submerged maps

**Expected behavior**
Submerged objects are correctly destroyed

**Screenshots**
This is a screenshot of the submerged object, I got after about 70 games(after playing MiraHQ) to check the bug(https://github.com/yukieiji/ExtremeRoles/issues/360) that exist in my mod.
![sudmerged objs 2024-09-28 230117](https://github.com/user-attachments/assets/3683321f-1152-4a97-8831-b1f168515511)
There are two pairs of the same object(WestLeftElevator and  EastRightElevator), so it seems that their destroying isn't done correctly

**Version (please complete the following information):**
 - Among Us: 2024.8.13
 - Submerged: 2024.8.26

**Log file**
[LogOutput.log](https://github.com/user-attachments/files/17174611/LogOutput.log)

**Additional context**
Unless you have dozens of submerged matches, this is not likely to cause memory leaks
However, it is possible that the freezes that occur when playing submerged are memory leaks caused by this.

**Comment by Alexejhero** [comment]
Where are these objects? Are they in HideAndDontSave? If so, regardless of how many times you launch Submerged, there should be no more created than there are already here.

**Comment by yukieiji** [comment]
I have not checked to see where it is.
But it's increasing as I play additional submerged...
![sudmerged objs 2024-09-28 230117](https://github.com/user-attachments/assets/09c7140f-1a4c-4968-b416-0c03cc81579a)

**Comment by Alexejhero** [comment]
Just to confirm, let's take `CreditsScreenManager` as an example, is that created multiple times?

**Comment by yukieiji** [comment]
> Just to confirm, let's take CreditsScreenManager as an example, is that created multiple times?

one time

> Where are these objects? Are they in HideAndDontSave? If so, regardless of how many times you launch Submerged, there should be no more created than there are already here.

I checked with UE and `hideflags` was `None`.

**Comment by Alexejhero** [comment]
You mentioned that "it's increasing as I play additional submerged..." but I am not sure I understand.
Are more and more ElevatorConsole objects being created, or is it just what you're showing me? 
In theory, there should only be 20 of them, maybe 40 if Submerged is currently loaded.

**Comment by yukieiji** [comment]
I'm sorry, sir.
I checked the logs carefully and found that these objects were present from the beginning of the game and did not change no matter how many games I played....
The image I sent you at the end also only seemed to increase.no problem.

It was my mistake and you are fine to close this.

**Comment by Alexejhero** [comment]
No worries! Thanks for keeping Submerged included in your modpack.
