### ISSUE TITLE
Submerged for Among Us 2024.10.29

### ISSUE THREAD

**Issue by Yougha789** [SubmergedAmongUs/Submerged#179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Yougha789** [comment]
When will Submerged be released for Among us 2024.10.29?

**Comment by Alexejhero** [comment]
Submerged does not need to be updated for 2024.10.29. The latest older of Submerged should work.

**Comment by Yougha789** [comment]
Ok
