### ISSUE TITLE
Out Of Bounds Glitch

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#18]
**Describe the bug**
can through the wall.(but can't back)

**To Reproduce**
1. Go to Lower Centrl(double elevator hallway to ballst's Decontamination)
2. Click "use" button
3. walk to door top
4. waiting door close
5. and you will get out from the door(through wall)

**Expected behavior**
no

**Screenshots**
https://drive.google.com/file/d/1xtWwES7NnLdPPF3qwp5UwA-Zhx8Vso9F/view?usp=sharing

**Version (please complete the following information):**
 - Among Us: 2022.3.29e
 - Submerged: 2022.5.8

**Log file**
no

**Additional context**
no

**Comment by nikkicarter11** [comment]
https://user-images.githubusercontent.com/106562207/171065685-f857453f-0366-4533-be4f-7a08c93b47d8.mp4

360p so it's small enough to upload, but this is repeatable for sure.

**Comment by NetherDragonTw** [comment]
5months ago...

**Comment by AlexejheroYTB** [comment]
It is very rare that this happens in regular games. I have tried fixing this issue two times in the previous updates and I'm not sure if it's still happening or not. This is just weird collider jankiness...

If this issue has not been fixed yet, it will probably not be for the time being.
