### ISSUE TITLE
can't open door

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#19]
**Describe the bug**
on upper lobby, you can't open door at outside or inside lobby.(just can use vent go to inside)
**To Reproduce**
1. as impostor, open sabotage menu, and close upper lobby door.
2. go to upper lobby(outside,inside) and use button was not highlighted.
3. can't move to door(like invisible wall?)
4. can't open door(door stucked)

**Expected behavior**
no

**Screenshots**
https://drive.google.com/file/d/1Kw0wx6BrR3XzjYTXqcmEZHZfWfivA900/view?usp=sharing
https://drive.google.com/file/d/1I4wCA0V_oJdtQxwf_xQ3oPK706J-kz6w/view?usp=sharing

**Version (please complete the following information):**
 - Among Us: 2022.3.29e
 - Submerged: 2022.5.15

**Log file**
no

**Additional context**
no

**Comment by AlexejheroYTB** [comment]
Fixed in v2022.5.16
https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.16
