### ISSUE TITLE
Submit translation: Simplified Chinese of the new 

### ISSUE THREAD

**Issue by ZeMingoh233** [SubmergedAmongUs/Submerged#2]
**What language(s) do you want to help us with?**
Simplified Chinese

**How can we contact you?**
_removed_

**Additional information**
Hello there, we're a group of amateur Chinese sinicization group. We‘re fans of Among Us and its mods, and have been devoted to translate all kinds of mods of Among Us like The Other Roles, Town Of Us and Las Monjas for a period of time. On hearing that many mods adds submerged map, we're pleasantly surprised and plan to translate it into Chinese. Could you please allow and adopt our translation for your map?We'll appreciate it if you consent and we guarantee that we will constantly produce translation for the future updates!

**Comment by AlexejheroYTB** [comment]
Simplified Chinese translations have already been submitted by someone else and will be available in the next update.
