### ISSUE TITLE
Reshelve Books Task Traditional Chinese Translation bug

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#20]
**Describe the bug**
on Medical, the yellow book name number was not displayed.

**To Reproduce**
1. go to freeplay
2. Click on computer
3. get Reshelve Books task
4. go to Medical
5. you will see yellow book name number was not displayed.

**Expected behavior**
no

**Screenshots**
![螢幕擷取畫面 (262)](https://user-images.githubusercontent.com/99878040/168601654-daf2334c-1de2-479e-83ef-91b3c8a2df69.png)

**Version (please complete the following information):**
 - Among Us: 2022.4.19e
 - Submerged: 2022.5.16

**Log file**
no

**Additional context**
[no](url)

**Comment by AlexejheroYTB** [comment]
Will be fixed in the next version.

**Comment by AlexejheroYTB** [comment]
Fixed in [v2022.6.12](https://github.com/submergedamongus/submerged/releases/v2022.6.12)
