### ISSUE TITLE
[Translation Offer] German

### ISSUE THREAD

**Issue by ItsNiceCraft** [SubmergedAmongUs/Submerged#21]
**What language(s) do you want to help us with?**
German (Germany)

**How can we contact you?**
ItsNiceCraft#0298

**Additional information**
I'm a native german speaker and would love to help!

**Comment by AlexejheroYTB** [comment]
Added in v2022.5.17
Thanks for the contribution!

https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.17
