### ISSUE TITLE
Plug Leaks Task Bug

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#22]
**Describe the bug**
can do task as task list doesn't display location.(like you need go to ballast but you can do the task at elec)

**To Reproduce**
1. Go to freeplay
2. get plug leakstask
3. next, if task list display location is on upper, open map(task map), if task list display location is on lower, go to upper and open task map
4. and you can do task at task list non-displayed location

**Expected behavior**
no

**Screenshots**
![螢幕擷取畫面 (267)](https://user-images.githubusercontent.com/99878040/168696921-1eea8f4b-75f7-4961-ab17-e1d3e40b306f.png)
this one is need to to ballast to complete task, but i can do at elec.

**Version (please complete the following information):**
 - Among Us: 2022.4.19e
 - Submerged: 2022.5.16

**Log file**
no
**Additional context**
no

**Comment by AlexejheroYTB** [comment]
This is intended behaviour. The task list only shows one of the 3 locations, but you can go to any of them and do the task in any order.

**Comment by NetherDragonTw** [comment]
ok thanks.
