### ISSUE TITLE
Bug with doors on The Skeld

### ISSUE THREAD

**Issue by Tommy-XL** [SubmergedAmongUs/Submerged#23]
**Describe the bug**
If you go to a random lobby on The Skeld map with a mod and get a traitor, then very strange things happen to the doors, for example, I could not close the doors at all, but at the same time others see that I closed them, and as shown in the video, in only the right door was closed in the dining room, and 2 others did not close, but other players had them closed

Note: I also noticed that if you are the owner of the lobby, then this problem does not arise.
And another, such problem only on The Skeld on other maps everything works fine

**Video**
https://drive.google.com/file/d/1o6dhTK45rJayY3T-ouljQJu7iIbhXG3U/view?usp=sharing

**Version (please complete the following information):**
 - Among Us: [2022.3.29s]
 - Submerged: [2022.5.17s]

**Comment by simonkellly** [comment]
Do the other members of the lobby have submerged installed?

**Comment by Tommy-XL** [comment]
No

**Comment by simonkellly** [comment]
Alright, I have identified and fixed the issue. It should be fixed in the next update (which we plan to release later today)

**Comment by AlexejheroYTB** [comment]
Fixed in v2022.5.18

https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.18
