### ISSUE TITLE
Possible Conflicts with CrowdedMod

### ISSUE THREAD

**Issue by MapleEve** [SubmergedAmongUs/Submerged#25]
**Describe the bug**
Older or latest Submerged is hard to load game with CrowdedMod and TOR-GM

**To Reproduce**
Install CrowdedMod and S v0518

**Expected behavior**
Game loaded and able to do online gaming

**Screenshots**
![image](https://user-images.githubusercontent.com/1845053/169231704-184929ef-10eb-4996-8140-dd619d75ce60.png)
Stuck in this screen forever

**Version (please complete the following information):**
 - Among Us:  2022.3.29s
 - Submerged: 0518
 - TOR GM-H 2.0.5.1
 - CrowdedMod v2.7.0

**Additional context**
Remove Submerged.dll and the game just run fine.

**Comment by AlexejheroYTB** [comment]
Submerged is not compatible with Crowded nor with TOR GM. Please contact the developers of those mods to add Submerged compatibility.

For a full list of what is compatible with Submerged, please check [the readme file](https://github.com/SubmergedAmongUs/Submerged#compatibility-with-other-mods).

**Comment by MapleEve** [comment]
> Submerged is not compatible with Crowded nor with TOR GM. Please contact the developers of those mods to add Submerged compatibility.
> 
> For a full list of what is compatible with Submerged, please check [the readme file](https://github.com/SubmergedAmongUs/Submerged#compatibility-with-other-mods).

TOR-GM-H is now support Submerged https://github.com/haoming37/TheOtherRoles-GM-Haoming/releases/tag/v2.0.10
So I need to contact Crowded :)
