### ISSUE TITLE
Vent bug

### ISSUE THREAD

**Issue by PHGaming121** [SubmergedAmongUs/Submerged#26]
i was playing on submerged with the town of us mod, but .... there's two glitched vents on the map
(Image 1) i cant enter in the central vent
![bug-1](https://user-images.githubusercontent.com/76562427/169364400-b03d540c-e45f-4d91-8d6b-782530ec18da.png)

(image 2) I just CAN ENTERr in this vent (cant enter without this mod)
![bug-2)](https://user-images.githubusercontent.com/76562427/169364673-dd9f22cf-9817-4439-b3b7-213363c87afb.png)

plz solve this in the next update

**Comment by simonkellly** [comment]
Submerged is not officially compatible with Town Of Us. Please contact the developer of that mods to add Submerged compatibility.

For a full list of what is compatible with Submerged, please check [the readme file](https://github.com/SubmergedAmongUs/Submerged#compatibility-with-other-mods).
