### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by Monid73** [SubmergedAmongUs/Submerged#3]
**What language(s) do you want to help us with?**
Let us know what language(s) you want to translate Submerged into.

### Hello! I want to translate that mod into Russian

**How can we contact you?**
Please leave an email or Discord tag that we can reach you at.

_removed_

**Additional information**
Add any other information here.

### I have experience in translating games, I translated the seventh and eighth parts of the games of the "Jackbox Party Pack" series in the team into Russian

**Comment by AlexejheroYTB** [comment]
Added in v2022.5.15. Thanks for helping us translate!
https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2022.5.15
