### ISSUE TITLE
Help with french translation

### ISSUE THREAD

**Issue by SuperLanceur** [SubmergedAmongUs/Submerged#31]
**What language(s) do you want to help us with?**
French

**How can we contact you?**
SuperLanceur#2865

**Additional information**
Nothing. Just let me know if I can help with the french translation !

**Comment by AlexejheroYTB** [comment]
Added in [v2022.6.12](https://github.com/submergedamongus/submerged/releases/v2022.6.12).

Thank you for your contribution!
