### ISSUE TITLE
Lower Central can't see shapeshifter's egg shadow

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#36]
**Describe the bug**
On Lower Central, you can't see shapeshifter shift egg in Upper Central's shadow.
**To Reproduce**
1. Go to Freeplay
2. make your shapeshifter
3. Go to Upper Central
4. use shift ability
5. see lower central's shadow, it was a player icon.

**Expected behavior**
no
**Screenshots**
no
**Version (please complete the following information):**
 - Among Us: 2022.4.19e
 - Submerged: v2022.6.12

**Log file**
Please attach the log file located in BepInEx/LogOutput.log
If you have restarted your game since you last encountered the issue, please try to reproduce the issue again and then upload the log.
no
**Additional context**
this will make in lower central crew don't know in Upper has people shift, please fix this.

**Comment by RobinRMC** [comment]
I just wanted to report the same thing. xD

**Comment by AlexejheroYTB** [comment]
So, when updating Submerged to support the new Among Us roles, we never considered whether or not the Shapeshifter's ability should be visible from the bottom.

As you might now, all cosmetics are hidden from players shadows. I'll speak to the rest of the developers and figure out if we want to make ability shadows visible or not.

**Comment by RobinRMC** [comment]
I personally think it would fit well. It's not a giveaway of who is doing it, but just showing that it happens.

**Comment by AlexejheroYTB** [comment]
Currently, the shadows on the bottom floor only reveal the players themselves and nothing else. Adding shadows for this ability would become a precedent which would need to be followed for future abilities as well. As such, we will not be implementing this.
