### ISSUE TITLE
Arabic translation.

### ISSUE THREAD

**Issue by AllawiEZ** [SubmergedAmongUs/Submerged#38]
**What language(s) do you want to help us with?**
I can help you with Arabic translation.

**How can we contact you?**
You can contact me on discord.
Discord username: Mr_Allawi_
Discord tag: 0194

**Additional information**
My timezone is AST-Arabia Standard Time. If you are contacting me at 2-9 am i might be asleep.

**Comment by AlexejheroYTB** [comment]
Currently, our translation system only allows us to translate Submerged into languages which are officially supported by Among Us itself. 

As Among Us does not yet have an Arabic translation, it means that unfortunately we cannot add such translations to Submerged.

If Innersloth adds Arabic translations into the future, we will be more than happy to add them for Submerged as well. But as of now, this is not possible.
