### ISSUE TITLE
Submerged won't open.

### ISSUE THREAD

**Issue by AllawiEZ** [SubmergedAmongUs/Submerged#39]
**Describe the bug**
I'm trying to play among us modded like the other roles, town of us and submerged only mod it self but every time i launch among us the unitycrashhandler appears then crashes among us!

**To Reproduce**
1- go to among us folder with submerged.dll inside the plugin folder of BepInEx
2- Launch the game
3- Wait for 3-10 seconds then crashes

**Expected behavior**
Because of old computer.

**Screenshots**
![image](https://user-images.githubusercontent.com/107771130/174643425-c2e9aba1-d0bb-4875-a55c-a2d53ac665ac.png)

**Version (please complete the following information):**
 - Among Us: 2022.3.29e
 - Submerged: 2022.6.12

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8942200/LogOutput.log)

**Additional context**
I tried everything and still won't open submerged map.

**Comment by simonkellly** [comment]
Does this issue occur when you remove all other mods from your among us and use the latest release from this repository?

**Comment by AllawiEZ** [comment]
Like i said i tried removed then putting it back i tried the other roles, town of us submerged and submerged alone but still won't work. And this happens every time i open it with Submerged.dll file in the plugin folder, If i play town of us without submerged i can't join people's lobbies i have to host my own and invite people.

**Comment by AllawiEZ** [comment]
> **Describe the bug** I'm trying to play among us modded like the other roles, town of us and submerged only mod it self but every time i launch among us the unitycrashhandler appears then crashes among us!
> 
> **To Reproduce** 1- go to among us folder with submerged.dll inside the plugin folder of BepInEx 2- Launch the game 3- Wait for 3-10 seconds then crashes
> 
> **Expected behavior** Because of old computer.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/107771130/174643425-c2e9aba1-d0bb-4875-a55c-a2d53ac665ac.png)
> 
> **Version (please complete the following information):**
> 
>     * Among Us: 2022.3.29e
> 
>     * Submerged: 2022.6.12
> 
> 
> **Log file** [LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8942200/LogOutput.log)
> 
> **Additional context** I tried everything and still won't open submerged map.

I found the only error in the logs is in this line: 117-121

**Comment by AlexejheroYTB** [comment]
That is not what is causing the crash. 

Please try removing Town of Us, Region Install and Reactor from the plugins folder, and run Among Us again. Afterwards, please upload a new log.

**Comment by AllawiEZ** [comment]
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8942403/LogOutput.log)

**Comment by AllawiEZ** [comment]
I made a new among us file put in submerged.zip ectracted it opened up among us and this is the result
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8942665/LogOutput.log)

**Comment by simonkellly** [comment]
Can you go to your appdata/locallow/innersloth/amongus and send the player log file?

**Comment by Tommy-XL** [comment]
I suspect the game is not licensed

**Comment by AllawiEZ** [comment]
What should i do?

**Comment by AlexejheroYTB** [comment]
I see that you are running Windows 7 32-bit. The crash might be due to your old system.

I will investigate the issue and let you know when I find the solution

**Comment by AllawiEZ** [comment]
Okay thank you

**Comment by AlexejheroYTB** [comment]
Your logs show no signs of crashing. 

Submerged has been tested and works on:
- Windows 7 64-bit
- Windows 10 64-bit

Additionally, Submerged should also work on:
- Windows 8 64-bit
- Windows 11 64-bit

Since you are running on an older 32-bit system, we cannot provide you support.
