### ISSUE TITLE
Add Controller support

### ISSUE THREAD

**Issue by Brybry16** [SubmergedAmongUs/Submerged#4]
**Is your feature request related to a problem? Please describe.**
You can't really play Submerged with a controller. The Tasks/Minigames don't allows Controller inputs and you can't select Sabotages with a controller.

**Describe the solution you'd like**
A way to play all the tasks and select sabotages with a controller

**Additional context**
Not really

**Comment by AlexejheroYTB** [comment]
When the tasks were designed, they were not designed with controller support in mind. There are even some tasks which require keyboard input (Reset Breakers, Record Nav Beacon Data, Door Sabotage). Adding controller support would require rewriting or redesigning most of the tasks and we might even need new art assets. As such, we unfortunately have no plans of adding controller support in the future.
