### ISSUE TITLE
Hat issues when looking from Upper Central to Lower Central

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#40]
**Describe the bug**
When looking at Lower Central player from Upper Central, Hat layer is not reflected correctly.
This result will be correct after doing ShapeShift

**To Reproduce**
1. Set a Hat that greatly changes the appearance of the Player.
2. Looking at that player from Upper Central.

**Expected behavior**
Hat rendering layer is incorrect.

**Screenshots**
- Screenshot looking at Lower Central from Upper Central(All player same hat)
![skinIssues](https://user-images.githubusercontent.com/40425798/175572075-41bfc9bf-03be-43af-977e-45da621c3298.PNG)

- Screenshot of Stillplant3 doing ShapeShifted to Stillplant1
![skinIssues_shapeshift](https://user-images.githubusercontent.com/40425798/175572541-509437b4-9e5a-4317-9f26-d645bc60319e.PNG)

- Screenshot of Stillplant3 with ShapeShift undone.
![skinIssues_shapeshift_after](https://user-images.githubusercontent.com/40425798/175572809-89e0940c-8385-47ad-aa62-7ceb44a02e01.PNG)

**Version (please complete the following information):**
 - Among Us: 2022.6.22e
 - Submerged: 2022.6.23
 - Extreme Roles v3.1.0.0 and Extreme Skins v3.1.0.0(https://github.com/yukieiji/ExtremeRoles/releases/tag/v3.1.0.0)

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8977494/LogOutput.log)

**Comment by AlexejheroYTB** [comment]
This looks like how it's supposed to work. Can you please describe the bug in more detail?

**Comment by AlexejheroYTB** [comment]
Yes, I see it now. This is indeed a bug.

**Comment by Tommy-XL** [comment]
These are the consequences of a bug in version 2022.6.21, The Skeld has the same problem on cameras

**Comment by AlexejheroYTB** [comment]
@yukieiji Is this issue still happening on the newest version? Please let me know.

**Comment by yukieiji** [comment]
Yes, this issue occurs even in the latest version

**Comment by AlexejheroYTB** [comment]
I am not sure if this issue is still present, but it will not be fixed for the time being.
