### ISSUE TITLE
Certain people become transparent.

### ISSUE THREAD

**Issue by Maximilian2022** [SubmergedAmongUs/Submerged#42]
**Describe the bug**
Certain people become transparent.

**To Reproduce**
Occurs occasionally.
It does not occur unless Submerged is included.
Occurs on non-Submerged maps.

**Expected behavior**
Survivors are visible to all other survivors.

**Version (please complete the following information):**
 - Among Us: 2022.3.29s
 - Submerged: 2022.4.9s

**Comment by AlexejheroYTB** [comment]
We are not accepting bug reports for versions other than the latest one. As you did not include reproduction steps, please upgrade to Submerged v2022.6.23 on Among Us v2022.6.21 and see if the issue still occurs.

**Comment by AlexejheroYTB** [comment]
You are on an older version of Among Us and Submerged and have not uploaded a log. It is impossible for us to try to reproduce or even debug the issue. Additionally, Submerged does not alter people's transparency in any way.

I am closing the issue for now as invalid. If you want to reopen, please post the following information:
- A log file
- A list of other mods you are using
- New version numbers, after you have updated to latest.
