### ISSUE TITLE
New Mod Compatibility

### ISSUE THREAD

**Issue by VincentVision** [SubmergedAmongUs/Submerged#46]
Hi I've made a modification of Town of Us Since v2.2.1 (before polus.gg mod) and now based on Town of Us Reactivated.
the mod is compatible with Submerged
you can find the repo here https://github.com/VincentVision/BetterTownOfUs

**Comment by simonkellly** [comment]
Hello, can you please detail how this mod differs from TOU-R which is already supported by submerged.

**Comment by VincentVision** [comment]
Yeah no problem

- Add a chat command "/set" to see the game settings in game.
- RNG Replacement for a better random genration.
- Lobby Timer.
- "Max Players" option to change the max players number directly in lobby.
- Default recommanded settings.
- "Better Polus" options.
     - "Vitals in Laboratory" option.
     - "Reactor vents are connected to buildings" option.
     - "New Tasks Positions" option.
- "Lycan" Imposotor Role.
- "Cannibal" Neutral Role.
- Lovers can't kill each other.
- "Jester Can Move In Vent" option.
- return to the old Arsonist.
- return to the old Seer.
- "Killing Neutral Can Guess" option.
- "Can Missing Guess 1 Time" option for the Impostor Assassin 1 per Team.
- "Who gets Guesser miss kill indicator" option for Miss Kill of the Impostor Assassin.
- Modify interval for Investigator's foot print size option from 2.5 to 0.25.
- Modify interval for Medic's report duration option from 2.5 to 0.5.
- A bunch of options for Engineer's fixes.
     - "Engineer Has A Vent Cooldown & Duration" option (like vanilla engineer).
     - "Custom" to "Engineer Fix Per" option.
     - "Engineer Have Cooldown" option for add a cooldown to Engineer.
     - "Engineer Cooldown" option to set the Engineer Cooldown if activated.
     - "Number of Fixes Per Round" option.
     - "Number of Fixes Per Game" option.
- Add kills timing on Vitals and cooldown/duration for Spy.
     - "Spy Cooldown" option.
     - "Spy Duration" option.
     - "Spy See Colors On Admin Table" option.
     - "Spy See Kills Timing On Vitals" option.
     - If colors and timing was deactivate, colors are automaticaly activated.
- Add shield display in meetings.
- "Jester & Executioner Can Spawn In Same Game" option to have only one of two without choose.
- "Medic Report Can't Have Name If Flashed By Grenadier" Medic have only darker or lighter color when he report while he flashed by Grenadier.
- Janitor, Lycan and Cannibal can't spawn in same game.
- New Panda color replace the Rainbow color.
- News customs hats.

**Comment by AlexejheroYTB** [comment]
Thank you for submitting this issue. We will add this mod compatibility to the readme when we update to among us 2022.8.24
