### ISSUE TITLE
Submerged doesn't work

### ISSUE THREAD

**Issue by DellyTheWorm** [SubmergedAmongUs/Submerged#47]
**Describe the bug**
After launching the game, there'll be a black screen, the icon in the task bar won't show, and instead of the Innersloth logo appearing, the game crashes.

**To Reproduce**
1. Install Submerged (BepInEx on its own works normally)
2. Launch the game

**Expected behavior**
The game opens normally, and the map is playable like the other 4 maps.

**Screenshots**
No screenshots.

**Version (please complete the following information):**
 - Among Us: [2022.7.12e]
 - Submerged: [2022.6.23]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/9337995/LogOutput.log)

**Additional context**
I have the Epic Games version of Among Us.

**Comment by simonkellly** [comment]
Hello,
Could you please try using the version of BepInEx which is provided in the Submerged.zip in the releases. That is the only version of BepInEx which we currently support.

**Comment by AlexejheroYTB** [comment]
I was about to reply as well.
The latest BepInEx version that is supported by Submerged is BepInEx  `6.0.0-be559`

**Comment by simonkellly** [comment]
I am going to close this issue for now. If you are still experiencing this issue after using the supported BepInEx version, please make another issue with an updated LogOutput file
