### ISSUE TITLE
Opening the settings menu makes the spawn in options invisible

### ISSUE THREAD

**Issue by Tommy-XL** [SubmergedAmongUs/Submerged#49]
**Describe the bug**
After the meeting, if you click on the setting, then the choice of location disappears and as a result the player has a black screen

**Video demonstration of the bug:**
https://drive.google.com/file/d/1DrrOjfsH655Q6XYIBcu8qU46FptNTgBP/view?usp=sharing

**Version:**
 - Among Us: [2022.8.24s]
 - Submerged: [2022.8.26s]

**Log file**
I don’t know if logs will be needed here or not, but I’ll upload it just in case

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/9437737/LogOutput.log)

**Comment by AlexejheroYTB** [comment]
Issue confirmed. A hotfix won't be released for this bug fix, but expect it to be fixed in the next version of Submerged.

**Comment by AlexejheroYTB** [comment]
This issue will be fixed in the next release. Thank you for reporting it.
