### ISSUE TITLE
I found mods that violate the rules.

### ISSUE THREAD

**Issue by Dekokiyo** [SubmergedAmongUs/Submerged#51]
https://github.com/ykundesu/SuperNewRoles
![snrsub](https://user-images.githubusercontent.com/97837904/194296335-2eaaf096-a72e-4f92-b093-46299bcf7bd5.png)

I think this violation to Submerged's licence Section 3 - b.
This code is gone now, but it was there until the other day.
Thank you very much.

**Comment by AlexejheroYTB** [comment]
Dekokiyo,
Thank you for bringing this to our attention.

After a quick examination of the offending code, we have determined that it is _not_ in violation of our license. As such, we will not be taking any action.

Thank you again for letting us know about it though, and have a great day!
- Alex
