### ISSUE TITLE
I can help Japanese Translation

### ISSUE THREAD

**Issue by Dekokiyo** [SubmergedAmongUs/Submerged#52]
**What language(s) do you want to help us with?**
Let us know what language(s) you want to translate Submerged into.

Japanese Translation

**How can we contact you?**
Please leave an email or Discord tag that we can reach you at.

Discord
𝑫𝒆𝒌𝒐𝑲𝒊𝒚𝒐#2745 (Since I use math symbols in my username, please copy and paste)

**Additional information**
Add any other information here.

I found Translation miss in this mod.
I want to fix it because it is unnatural.

**Comment by AlexejheroYTB** [comment]
Thank you for your help! Your translations will be added into the next version of Submerged, which will be released soon.
