### ISSUE TITLE
Microwave Lunch Task

### ISSUE THREAD

**Issue by CurtPower** [SubmergedAmongUs/Submerged#53]
I don't know how to complete the 'Microwave Lunch' Task.
The only thing I know what to do is to input how long to microwave the pizza.
Can someone explain to me how to complete the task?

**Comment by AlexejheroYTB** [comment]
The microwave lunch task is similar to the Inspect Sample task on Skeld and Polus. The idea is that you enter the correct time to start the task, and then you can leave it. Once that time has passed, you have to return back to the task and click on the food item that was cooked to finish it

**Comment by Tommy-XL** [comment]
![C2qGr3-KY0M](https://user-images.githubusercontent.com/104814436/198832175-28f31ec4-2503-4d20-a0bc-c1f3c6242863.jpg)
