### ISSUE TITLE
Add Compatible MOD

### ISSUE THREAD

**Issue by Lunastellia** [SubmergedAmongUs/Submerged#54]
Hii, Could you add "Challenger" to compatibility mods?

https://github.com/Lunastellia/Challenger-Among-Us

Thank you.

**Comment by AlexejheroYTB** [comment]
Will be added. 👍

**Comment by Alexejhero** [comment]
Sorry, the plan was to add the mod as compatible when we updated the readme for the next release, but in the next release we are removing the compatibility table from the readme.
