### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by toususmaster** [SubmergedAmongUs/Submerged#57]
**What language(s) do you want to help us with?**
I can help with Polish(Polski) translation

**How can we contact you?**
on discord Vuvex#3252 , mail dsdffdg269@gmail.com

**Additional information**
Im Polish gamer and I would be happy when there would be a Polish translated mod

Thanks for Reading,
Vuvex :0

**Comment by AlexejheroYTB** [comment]
Hey, as mentioned in #17, unfortunately we cannot add Polish translations for Submerged since Among Us itself doesn't support Polish translations.
