### ISSUE TITLE
Submerged map not showing in main menu

### ISSUE THREAD

**Issue by NixPlayer** [SubmergedAmongUs/Submerged#58]
The submerged map is not showing, when i click on freeplay or find game, the submerged map is not showing, but the mod is installed properly and the impostor with the "mod" sign under it is showing.

Open Among Us
Go onto freeplay
No submerged map showing
Or
Go to online
Go to find servers
No submerged map showing

 - Among Us: [v2022.12.14e]
 - Submerged: [v2022.10.26]

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/10329446/LogOutput.log)

I think, now that i've wathced the log file, that submerged is missing a dependency that the newer versions of among us needs

**Comment by AlexejheroYTB** [comment]
Submerged has not been updated to Among Us 2022.12.14 yet. 

If you want to use Submerged you will have to downgrade your Among Us version. If you are on steam please switch to the "public-previous" branch. If you are on epic unfortunately you cannot downgrade so you will have to wait for us to update.

**Comment by AlexejheroYTB** [comment]
Issue #56 is being used to track progress of the update, so I will close this one.
