### ISSUE TITLE
I can't play online

### ISSUE THREAD

**Issue by zozogame1** [SubmergedAmongUs/Submerged#62]
**Describe the bug**
When I'm trying to play online, it's says that there is a problem with reactor and Among us give me a link: https://docs.reactor.gg/guides/handshake

**To Reproduce**
1. Go to 'Online'
2. Click on 'Find game'
3. You'll see the error
**Expected behavior**
I thought I could play online

**Screenshots**
I can't, because my version doesn't match the map version anymore (because of the update) 

**Version (please complete the following information):**
 - Among Us: [e.g. 2022.10.25s]
 - Submerged: [e.g. 2022.10.26s]

**Log file**
As I said before, I can't, because my version doesn't match the version of the map (because of the update), so I can't reproduce the bug.

**Additional context**
I hope you can help me even with the little information I have provided.
 Sorry if my english is bad, I'm using a translator (I'm french)

**Comment by AlexejheroYTB** [comment]
That errors appears when trying to use mods on official servers, but it should not prevent you from playing online.

**Comment by zozogame1** [comment]
On the list of servers, I have only the official servers
So, how can I fix it?

**Comment by AlexejheroYTB** [comment]
You can ignore the error and play as normally.

**Comment by zozogame1** [comment]
Ok, I'll test when the map will be updated

**Comment by whichtwix** [comment]
you cant use the find game button, the lobbies shown will have ppl who wont have submerged installed, if you want to use it you have to go on a custom server like modded na, eu, or asia

**Comment by zozogame1** [comment]
I know I have to go in the moded servers, but there's only the official servers.

**Comment by zozogame1** [comment]
![Screenshot_2023-03-05-09-35-54-682_com innersloth spacemafia](https://user-images.githubusercontent.com/122510378/222950411-1e1fa98b-9efb-4ffb-a1a4-ac170664c017.jpg)

Don't pay attention to the version and skeld.net (I took this screenshot on my phone because I don't have my computer with me) (without skeld.net, it's all the servers I see) (on my computer with the map installed)

**Comment by whichtwix** [comment]
you can get the custom servers either by also downloading a mod like tou, tor, or las monjas, or starting your own

**Comment by AlexejheroYTB** [comment]
However as I mentioned before custom servers are not entirely necessary, as the map will work correctly on official servers.

**Comment by whichtwix** [comment]
yes, but the person brought up the find a game button primarily which is why im saying

**Comment by zozogame1** [comment]
Ok, when the map will be updated, I will download a mod to see if it works
Can "Town Of Us Reactivated" work?

**Comment by whichtwix** [comment]
ye

**Comment by GD825** [comment]
as of now, no mods have submerged, as its still being worked on to be updated to work with the latest versions, when its ready, those mods will post an updated release with it

**Comment by zozogame1** [comment]
Ok
