### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by AppcircleUser** [SubmergedAmongUs/Submerged#70]
ok so recently I found this mod and decided to try it with a pirated version of Among Us and it didn't work. So now I want to buy Among Us to play this mod as well as BetterPolus and now I'm wondering if the mod still works on the latest version of Among Us.

**Comment by AppcircleUser** [comment]
ok so someone on the BetterPolus GitHub helped me and said that Submerged doesn't work with the newer versions.

**Comment by haaldor** [comment]
Submerged is not yet up-to-date, If you look at the "Issues" tab first issue on the top (named "[Update to Among Us 2022.3.28 #56](https://github.com/SubmergedAmongUs/Submerged/issues/56)"), is a to-do list of tasks to be done for Submerged to be ready for Among Us 2023.3.28 (yeah, there's typo in version name in the issue).
Till all of them are done, Submerged is outdated.
