### ISSUE TITLE
When will you open the beta test?

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#73]
When will you open the beta test?

**Comment by Alexejhero** [comment]
We're waiting on https://github.com/BepInEx/Il2CppInterop/pull/92 to get merged, as well as the new version release for https://github.com/NuclearPowered/Reactor. In the meantime we're working on improving the codebase and the performance of the mod.

**Comment by Wael1231** [comment]
what if the pull dosent merged what you will do for Submerged ?

**Comment by Wael1231** [comment]
so if the BepInEx/Il2CppInterop#92 won't to merge i have my own custom repo of Il2CppInterop that merge the Pools object... 
https://github.com/Wael1231/Il2CppInterop
