### ISSUE TITLE
Shapeshift button bug

### ISSUE THREAD

**Issue by NetherDragonTw** [SubmergedAmongUs/Submerged#74]
**Describe the bug**
1.while shapeshifting, if you are try to unshift, your button was stuck on the shapeshifting styles.
2.if you let the ability automatically unshift, the button will disappear.

Screenshot:
![圖片](https://github.com/SubmergedAmongUs/Submerged/assets/99878040/50e8a494-71b2-4c46-96c8-31877261548a)
![螢幕擷取畫面 2023-06-20 184840](https://github.com/SubmergedAmongUs/Submerged/assets/99878040/14833514-8af4-43a2-8359-e3c87a3ea01b)

 - Among Us: 2023.6.13e
 - Submerged: Submerged v2023.6.20-beta.1

**Comment by Alexejhero** [comment]
Cannot reproduce

**Comment by NetherDragonTw** [comment]
> Please upload your log file so we can identify the issue. The log file is found in your Among Us folder, in BepInEx/LogOutput.log

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11811924/LogOutput.log)

**Comment by Alexejhero** [comment]
Hmm, there's nothing here. Could you also please upload the Unity log, found in `%userprofile%/AppData/LocalLow/Innersloth/Among Us/Player.log`?

**Comment by NetherDragonTw** [comment]
> 
[Player.log](https://github.com/SubmergedAmongUs/Submerged/files/11814802/Player.log)

**Comment by Alexejhero** [comment]
Are you able to reproduce this issue in the beta.2 version?

**Comment by NetherDragonTw** [comment]
> Are you able to reproduce this issue in the beta.2 version?

yep, i have test it in beta.2
here is the log:
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11827011/LogOutput.log)
[Player.log](https://github.com/SubmergedAmongUs/Submerged/files/11827013/Player.log)

**Comment by chillultimated** [comment]
the same thing happens to engineer's icon when time limit in vents set to infinitely

**Comment by Alexejhero** [comment]
![](https://cdn.discordapp.com/emojis/788159338211967036.webp?size=100)

**Comment by Alexejhero** [comment]
What game options are you using?

**Comment by chillultimated** [comment]
> 

> What game options are you using?

You mean lobby settings?

**Comment by Alexejhero** [comment]
yes

**Comment by chillultimated** [comment]
> yes

Sorry, I can't send you right now, I'm not at home, I'll send when I'll come back

**Comment by chillultimated** [comment]
> What lobby settings are you using?

![изображение_2023-06-25_175929680](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/0d16f342-8b7a-430b-a285-8bb049d188e6)

**GA:**
Protect cooldown - 35s
Protect duration - 30s
Protect visible to Impostor - off

**Engineer:**
Vent use cooldown - changing every game but usually its 5, 10 or 15
Max time in Vents - ∞ (yes, there's a way to do this in vanila)

**Shapeshifter:**
Shapeshift duration - ∞ (yes, there's a way to do this in vanila, I can send you a video)
Shapeshift cooldown - 5s
Leave shapesifting evidence - on

**Scientist (off but still):**
Vitals display cooldown - 5s
Battery duration - 20s

**Comment by NetherDragonTw** [comment]
so is this will be fixed?

**Comment by chillultimated** [comment]
> so is this will be fixed?

idk dude, Im not dev, dont ask me

**Comment by Alexejhero** [comment]
Once I am able to reproduce the issue I will fix it

**Comment by chillultimated** [comment]
> Once I am able to reproduce the issue I will fix it

if you want to reproduce the same issue but with engineer then:
1. set max time in vents to ∞
2. jump in the vent and then make an emergency meeting
3. thats it. It should appear after that

**Comment by Alexejhero** [comment]
This is a base-game issue, it happens even without submerged installed lmao

**Comment by NetherDragonTw** [comment]
bruhhhhh

**Comment by Sand-and-Beans** [comment]
> bruhhhhh

这个确实是among us自己的bug
