### ISSUE TITLE
Hat/outfit/pet layering issues in the shop menu

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#75]
Hat is supposed to be over the pet and skin

**To Reproduce**
Go to the shop

**Expected behavior**
I just opened the shop
![Снимок экрана 2023-06-20 211500](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/b470c0fd-46cc-46ea-99a6-6b3a0cec5bf9)

**Version:**
 - Among Us: 2023.6.13s
 - Submerged: 2023.6.20-beta.1

**Comment by tartsharpcobra** [comment]
Is this even a big deal?

**Comment by Alexejhero** [comment]
No but we have similar layering issues with hats/outfits/visors in-game, in upper central and on cams

**Comment by chillultimated** [comment]
> No but we have similar layering issues with hats/outfits/visors in-game, in upper central and on cams

umm yes? 
1 picture: original Among Us
2 picture: Submerged mod installed

![1](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/846421a2-4ef2-42f0-96ba-d0f084c5338c)

![2](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/55c8d96e-e831-48df-b36a-feb28bccaec1)

**Comment by chillultimated** [comment]
also I was a bit wrong: fiest layer is pet, second is skin and the last one is the hat.

**Comment by chillultimated** [comment]
> Is this even a big deal?

no but its still a bug

**Comment by Alexejhero** [comment]
Fixed in https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.6.25-beta.3 alongside other layering issues (hopefully)
