### ISSUE TITLE
The camera monitor screens are purple

### ISSUE THREAD

**Issue by zozogame1** [SubmergedAmongUs/Submerged#76]
**Describe the bug**
The camera monitor screens are purple.

**To Reproduce**
1. Go to the security
2. Click on "Camera"
3. And you'll see that the screens are purple.

**Expected behavior**
I thought the screens would display the cameras.

**Screenshots**
![Capture d'écran 2023-06-20 132044](https://github.com/SubmergedAmongUs/Submerged/assets/122510378/363f0c3b-1232-4871-98e5-96f4d641f9f5)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.13s]
 - Submerged: [e.g. 2023.6.20-beta.1]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11800031/LogOutput.log)

**Comment by PHGaming121** [comment]
same here

**Comment by Alexejhero** [comment]
Fixed in https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.6.20-beta.2
