### ISSUE TITLE
CANT LEAVE THE ELEVATOR

### ISSUE THREAD

**Issue by PHGaming121** [SubmergedAmongUs/Submerged#77]
**Describe the bug**
When i enter an elevator, i get stuck in.

**To Reproduce**
1. Go to 'Submerged map'
2. Enter and use an elevator
3. Get stuck in there forever

**Expected behavior**
Go up/down and open the door again.

**Screenshots**
here
![Captura de Tela (381)](https://github.com/SubmergedAmongUs/Submerged/assets/76562427/441b7a37-ac3f-4ece-aa80-4715f811fe71)

**Version (please complete the following information):**
 - Among Us: [v2023.6.13]
 - Submerged: [v2023.6.20-beta.1]

**Log file**
cant upload because too big

**Additional context**
Im using Town Of Host Edited too.

**Comment by PHGaming121** [comment]
BRO
IT SAYS THAT THE LOG FILE IS TOO BIG

**Comment by Alexejhero** [comment]
How big is it

**Comment by Alexejhero** [comment]
You are using an old version of the `BepInEx/core/Il2CppInterop.*.dll` files. Please use the ones from the Submerged release instead

**Comment by tartsharpcobra** [comment]
lmao
