### ISSUE TITLE
[Visual] A button to display Credit can be pressed at anywhere in the main menu

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#79]
**Describe the bug**
A button to display Credit can be pressed at any time.

**To Reproduce**
1. boot AmongUs
2. Click on 'Play'
3. Click on 'Credit buttons'

**Expected behavior**
It would be nice if the button couldn't be pressed or show when 'Play' or 'MyAccount' is being pressed.

**Screenshots**
It is a little to the left of my mod, but I have not made any changes other than the location.
https://github.com/SubmergedAmongUs/Submerged/assets/40425798/3886e99b-6ac1-4057-bdf8-64bbfa36f06d

**Version (please complete the following information):**
 - Among Us: [e.g. 2022.3.29s] 2022.6.13
 - Submerged: [e.g. 2022.4.9s] v2023.6.20-beta.2

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11819700/LogOutput.log)

**Additional context**

**Comment by Alexejhero** [comment]
Will be updated soon

**Comment by Alexejhero** [comment]
Hiding/showing the button based on the active menu looks weird, so instead i reduced the scale of the button from 1.2 to 0.9

If the button overlaps with other UI elements you can move it around or make it smaller, or even replace it with a traditional UI button if you want.

Will be updated in the next version.

**Comment by yukieiji** [comment]
Thank you!!

**Comment by Alexejhero** [comment]
Updated in https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.6.25-beta.3
