### ISSUE TITLE
Modded servers do not show up (beta-2)

### ISSUE THREAD

**Issue by tartsharpcobra** [SubmergedAmongUs/Submerged#80]
The modded servers (MNA, MEU, and MAS) Do not show up in the regions menu. Therefore, you cannot access servers w/ modded handshake.

**Comment by Alexejhero** [comment]
That's intentional. Submerged can run on officials.

**Comment by tartsharpcobra** [comment]
Did not know that. Im trying to run it w/ TOuR

**Comment by Alexejhero** [comment]
TOUR hasn't even updated for the latest version yet ......

**Comment by tartsharpcobra** [comment]
no wonder it kept crashing ._.
