### ISSUE TITLE
Cosmetics pass through objects and players

### ISSUE THREAD

**Issue by zozogame1** [SubmergedAmongUs/Submerged#81]
**Describe the bug**
Well, the cosmetics pass through objects and players

**To Reproduce**
1. Equips any cosmetic (clothes or pets)

**Expected behavior**
Nothing

**Screenshots**
![Capture d’écran 2023-06-22 103040](https://github.com/SubmergedAmongUs/Submerged/assets/122510378/d6e5cc1d-b8be-47ef-bfdc-316ba81325d9)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.13s]
 - Submerged: [e.g. 2023.6.20-beta.2]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11831101/LogOutput.log)

**Comment by Alexejhero** [comment]
This is not an issue, this is what happens in regular among us as well.
