### ISSUE TITLE
I can't connect to the modded US server

### ISSUE THREAD

**Issue by zozogame1** [SubmergedAmongUs/Submerged#82]
**Describe the bug**
When I try to connect to the modded US server, it disconnects my Among Us account and gives me an error.

**To Reproduce**
1. Go to 'Play'
2. Click on the modded US server in the list of server
3. Click on "Find Game"

**Expected behavior**
I thought I was going to be able to play.

**Screenshots**
![Capture d'écran 2023-06-22 103246](https://github.com/SubmergedAmongUs/Submerged/assets/122510378/c57ad749-29ad-4636-8651-4fc1aa1d3af5)
![Capture d'écran 2023-06-22 103328](https://github.com/SubmergedAmongUs/Submerged/assets/122510378/51ed3de3-b3ff-4f41-9698-ee3b35003a40)
![Capture d'écran 2023-06-22 103403](https://github.com/SubmergedAmongUs/Submerged/assets/122510378/0eccab42-eeb8-421d-b5d8-0924d8f4282b)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.13s]
 - Submerged: [e.g. 2023.6.20-beta.2]

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11831800/LogOutput.log)

**Additional context**
I don't know if it's normal or not, but when I'm trying to find a game, there is no loby. Probably normal.

**Comment by tartsharpcobra** [comment]
Same problem.
