### ISSUE TITLE
Pet in the elevator bug

### ISSUE THREAD

**Issue by DoudaKarma** [SubmergedAmongUs/Submerged#83]
**Describe the bug**
While in the elevator i pet my pet and walked forward while the elevator was opening and then i just got stuck walking forward forever (when the impostor kills me they clip outa the map)

**To Reproduce**
1. Go to upper lobby and go down
2. Click on pet while on the elevator and walk forward 
3. You should normally be stuck going forward forever 

**Expected behavior**
To be able to walk normally after i pet my pet

**Screenshots**
I will provide a video of what's happening in the discussion 

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.13s]
 - Submerged: [e.g. 2023.6.20-beta.2s]

**Comment by DoudaKarma** [comment]
https://github.com/SubmergedAmongUs/Submerged/assets/108459525/ad8b883e-e969-402c-b3c9-3b23f2d0e002

**Comment by DoudaKarma** [comment]
it works with every elevators

**Comment by Alexejhero** [comment]
I can't even use the pet button, the petting animation doesn't play

**Comment by DoudaKarma** [comment]
That's weird me and my friends are able to use it

**Comment by Alexejhero** [comment]
Could you please explain the reproduction steps? So you have to hold forward and spam click the pet button or... how do you get that issue? Also is it easy to reproduce or does it happen rarely?

**Comment by DoudaKarma** [comment]
So i pet my pet when the doors is about to open and i hold forward

**Comment by Alexejhero** [comment]
The issue has been identified and fixed for the next release.

**Comment by Alexejhero** [comment]
"Fixed" in https://github.com/SubmergedAmongUs/Submerged/releases/tag/v2023.6.25-beta.3

(You can no longer pet while in the elevator)
