### ISSUE TITLE
[Visual improvement] Shapeshifting animation for players' shadows

### ISSUE THREAD

**Issue by tartsharpcobra** [SubmergedAmongUs/Submerged#84]
**Is my feature request related to a problem? Not exactly.**
When you are on the upper floor, Shapeshift. Pat attention to your shadow as the shapeshift does not show on your shadow.

**Here is my solution.**
Id like to add some extra animation to the players' shadow to show players visibly shapeshifting.

**Image:**
![Screenshot 2023-06-22 134405](https://github.com/SubmergedAmongUs/Submerged/assets/80216776/7ae9026e-9481-4771-afcb-ef5b4437e8ad)

Aaaand that's it!

**Comment by Alexejhero** [comment]
As mentioned in #36, we don't want to add shadows for animations such as the shape shifter egg, for a few reasons:
1. Precedent - adding shadows for the shapeshifter egg would mean that we would need to also add shadows for any future abilities that are introduced
2. Limiting information - while we want the central glass to be a way crewmates can gain information, seeing impostor abilities is too much in our opinion

Plus it would have the chance to give crewmates information without impostors knowing - an impostor in the south part of upper central could shapeshift thinking that it's safe, but their shadow could be seen by a crewmate in the north part of storage.

**Comment by tartsharpcobra** [comment]
did not know that :/
