### ISSUE TITLE
Hat/outfit/pet layering issues in the shop menu

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#90]
![orig](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/315a5577-a268-43ae-bc79-6f0df3b6aac0)
![SUB](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/60c7b0e5-be1b-4b0b-bb7d-ee85e18d5019)

**Describe the bug**
This issue still didnt fixed

**To Reproduce**
Go to the shop

**Expected behavior**
everything is on the pictures

**Version (please complete the following information):**
 - Among Us: 2023.6.13s
 - Submerged: 2023.6.25-beta 3

**Comment by Alexejhero** [comment]
Closing in favor of #87 

We aren't touching the shop menu in any way plus I don't really care about this problem, if it happens to get fixed when we fixed the other layering issues then fine otherwise I will leave it as it is
