### ISSUE TITLE
Clickable names in credits

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#91]
![Снимок экрана 2023-06-26 171831](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/f6aaf453-5200-42a4-85ec-7996c4c689cc)

A feature that allows you to click on the name in credits menu and it'll lead user to the webpage
(example: if you click on "5up", a browser will open for you, and a tab with a 5up YouTube channel will open in this browser)

**Comment by Alexejhero** [comment]
Not implementing
