### ISSUE TITLE
This task makes no sence

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#92]
![Снимок экрана 2023-06-26 174608](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/69b087ed-1f30-445a-8a97-7b430b91d7b3)

in previous task I downloaded data to my **tablet** and uh... why am I holding a phone from the Airship? (yes, tablet and this phone are 2 different things)

also why am I looking for a better internet UNDER WATER?

**Comment by ArslanShakirov** [comment]
lol

**Comment by Alexejhero** [comment]
This task was originally meant to be regular upload but was changed to airship upload because that task is more interesting. I agree it makes no sense but whatever, it also doesn't make any sense to have a room called "Ballast" in an underwater building
