### ISSUE TITLE
Error Reactor

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#95]
![20230627112638_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/099a270e-0d7d-4b3c-9a26-e36bf2741df9)
the reactor gives this error

**Comment by AlchlcDvl** [comment]
it means that the the server you are trying to play on do not handle the modded data being sent over during games, switch over to a different region that can handle the modded info

**Comment by ArslanShakirov** [comment]
> it means that the the server you are trying to play on do not handle the modded data being sent over during games, switch over to a different region that can handle the modded info

so the developers of the mod said that the submarine supports the official servers

**Comment by NetherDragonTw** [comment]
this is not an error, it just reactor's warning information.
the submerged its still working on offical server.

**Comment by chillultimated** [comment]
> > it means that the the server you are trying to play on do not handle the modded data being sent over during games, switch over to a different region that can handle the modded info
> 
> so the developers of the mod said that the submerged supports the official servers

it works on the official servers (europe, north america and asia) but you can only play in private lobbies

**Comment by Alexejhero** [comment]
This is from Reactor and it's not an error
