### ISSUE TITLE
There's a bad thing I want to tell you (Not about creating this mod) 

### ISSUE THREAD

**Issue by Sand-and-Beans** [SubmergedAmongUs/Submerged#96]
Dear officials of Submerged, 

I'm an Among Us player from China. What I want to tell you is that your map was pilfered by a trashy pirate game here (in China). The game is called "Super Sus" (Chinese: 太空行动). This game copies everything from app label to characters and to the skins and to the roles and the maps and even your Submerged. I can interfere that this pirate game didn't contact with you about using this map and just put it in their games directly. I can't bear this behavior of copying not only the original game and even the mod. Ok, in this message, I just want to tell you about this. 

Thank you,
Mousse

**Comment by NetherDragonTw** [comment]
我已經跟他們說過了
他們說他們也沒有辦法
![Screenshot_20230628-000733~2](https://github.com/SubmergedAmongUs/Submerged/assets/99878040/4d2a409e-9378-46e7-b19e-7fa1ecaccac8)
![Screenshot_20230628-000723~2](https://github.com/SubmergedAmongUs/Submerged/assets/99878040/4e322f6f-6809-4152-a8e4-1d9d5e391c8a)

**Comment by Alexejhero** [comment]
Yeah we're aware of this but we can't do anything about it

**Comment by chillultimated** [comment]
> Yeah we're aware of this but we can't do anything about it

can't you type to Super Sus creators and ask to remove the map?

**Comment by Alexejhero** [comment]
no

**Comment by chillultimated** [comment]
> no, it doesn't work like that

okay, sorry

**Comment by Alexejhero** [comment]
https://www.bilibili.com/video/BV1G34y1n7B7/

**Comment by Sand-and-Beans** [comment]
> > Yeah we're aware of this but we can't do anything about it
> 
> can't you type to Super Sus creators and ask to remove the map?

I also tried but there's no use and they even blacklisted me. I told Innersloth about the copying behavior and they responded that they will deal with this later but nothing happened. I think they also can't do anything about it. Too many people have no copyright awareness in here (I think you can guess what "here" means and it's real, even I know saying this will make some "dogs" angry.)
