### ISSUE TITLE
Change admin table

### ISSUE THREAD

**Issue by chillultimated** [SubmergedAmongUs/Submerged#98]
![Снимок экрана 2023-06-26 174124](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/0ecc34e8-31e4-4a69-aa7b-d2f4de0b5cc5)

Icons on the admin tablet in the submerged map are outdated. New versions of Among Us using gray icons instead of yellow.

![изображение_2023-06-28_112231850](https://github.com/SubmergedAmongUs/Submerged/assets/86905561/ae310c67-5889-4311-8e8e-d20f97ff8bcc)

**Comment by Alexejhero** [comment]
Thanks for the report, will be updated in the next version
