### ISSUE TITLE
The microwave task does not work 

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![20230701150747_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/cd841e36-45e0-44e0-90de-91ab2e6eeb00)

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.6.27s]
 - Submerged: [e.g. 2022.4.9s]

**Log file**

[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11925551/LogOutput.log)

**Additional context**
The microwave task does not work

**Comment by Alexejhero** [comment]
What doesn't work about the task?

**Comment by ArslanShakirov** [comment]
not fulfilled

**Comment by Alexejhero** [comment]
If you do not describe the issue there is no way I can fix it

**Comment by ArslanShakirov** [comment]
> If you do not describe the issue there is no way I can fix it

microwave job not running
